# Generated by Django 5.0.3 on 2024-03-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The name of the event.", max_length=200
                    ),
                ),
                ("description", models.TextField()),
                ("startdate", models.DateField()),
                ("enddate", models.DateField()),
                (
                    "organizer",
                    models.CharField(
                        help_text="The organizer of the event. Could be religeous institution, art institutions or any other.",
                        max_length=200,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                (
                    "website",
                    models.URLField(help_text="The Event's associated website."),
                ),
            ],
        ),
    ]
