# Generated by Django 5.0.3 on 2024-03-26 10:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The name of the organizer.", max_length=200
                    ),
                ),
                ("description", models.TextField()),
                (
                    "organizer",
                    models.CharField(
                        help_text="The organizer of the event. Could be religeous institution, art institutions or any other.",
                        max_length=200,
                    ),
                ),
                ("address1", models.CharField(max_length=200)),
                ("address2", models.CharField(max_length=200)),
                ("zip_code", models.CharField(max_length=6)),
                ("poly", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                (
                    "website",
                    models.URLField(help_text="The Event's associated website."),
                ),
            ],
        ),
    ]
