# Generated by Django 5.0.3 on 2024-03-26 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0002_organizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                help_text="The organizer of the event. Could be religeous institution, art institutions or any other.",
                on_delete=django.db.models.deletion.CASCADE,
                to="temples.organizer",
            ),
        ),
    ]
